apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
- namespace.yaml
- mysql.yaml
- wordpress.yaml

secretGenerator:
- name: app-tls
  literals:
    - MYSQL_ROOT_PASSWORD=password1234
  type: Opaque
